#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
#adaptor=${0##*/}
adaptor="adaptor.js"

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/$adaptor" "$@"
  ret=$?
else
  node  "$basedir/$adaptor" "$@"
  ret=$?
fi
exit $ret
