#!/bin/sh

# This script file is to be used as a value for a symlink on Windows systems. This symlink is intended
# to reside in the $ENV:Path so that it can be called in the CLI as a command.
#
# This script file, along with it's sibling (bash) file for UNIX systems, takes the filename
# of the symlink, current directory and parses the symlink.config.json file. With the information
# gathered, it will call the JS adaptor file with node. This adaptor file must reside in the
# 'projectOutPath' directory which is relative to the current directory.
#
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
#adaptor=${0##*/}
adaptor="adaptor.js"

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/$adaptor" "$@"
  ret=$?
else
  node  "$basedir/$adaptor" "$@"
  ret=$?
fi
exit $ret
