#!/usr/bin/env node
/*
const { exec } = require('child_process');
exec('yarn versions', (err, stdout, stderr) => {
  if (err) {
    // node couldn't execute the command
    return;
  }

  // the *entire* stdout and stderr (buffered)
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
*/

/**
 *
install cordova-android@7.1.1 --production --save-exact
console.log(process.argv);
*/
