#!/bin/bash

PROGRAM=`basename "$0"`
DIR=`pwd`
while [ ! -x "$DIR/node_modules/.bin" ]; do
  DIR=`dirname "$DIR"`
  if [ "$DIR" = "/" ]; then
    echo "Local node program not found: $PROGRAM" 1>&2
    exit 1
  fi
done

exec "$DIR/node_modules/.bin/$PROGRAM" "$@"